### ISSUE TITLE
'Using the ShiftLeft CLI' link broken

### ISSUE THREAD

**Issue by Ropes** [ShiftLeftSecurity/documentation#123]
I noticed that there's a broken link in the docs on the first link of the page: `Use ShiftLeft Inspect to submit applications for analysis and profiling.` Leads to a Github 404 page. 

* Docs page: [Using the Shiftleft CLI](https://docs.shiftleft.io/shiftleft/using-shiftleft-inspect-and-shiftleft-protect/using-cli)
* Broken [link](https://github.com/ShiftLeftSecurity/documentation/tree/daf6361cba166e385d207b3bb85435ef881863e3/using-inspect-protect/analyzing-applications-in-ci.md)

I'm not sure what the fix is, I'm guessing a relative address might have changed?

**Comment by NWeber-SL** [comment]
Thanks for heads up. Fixed in branch updates-fixes, not merged yet.
