### ISSUE TITLE
API reference link should point to package root

### ISSUE THREAD

**Issue by fabsx00** [ShiftLeftSecurity/documentation#23]
In the section "Using ShiftLeft Ocular"  the link "Ocular API" currently points to

https://ocular.shiftleft.io/api/io/shiftleft/queryprimitives/index.html

but should point to

https://ocular.shiftleft.io/api/

I'm not sure how to change this, so I'm opening an issue instead.

**Comment by NWeber-SL** [comment]
Fixed in Pull Request #28
